version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: ${BOT_TOKEN}
    volumes:
      - ./:/app/
      - /app/node_modules
  chrome:
    image: yukinying/chrome-headless
    ports:
      - "9222:9222"